Refactor with ES6
IfzaRasool/Awesome-Books-With-ES6 pull request #1
Opened 2022-03-21 21:13 UTC by IfzaRasool

**Refactor with ES6**
- Create Modules folder
- Add JS Modules files
- Add luxon Library for date
- Use Arrow function
- Use let and const

2022-03-21 21:51 UTC, GzimAsani requested changes
# Hi @IfzaRasool          
Good job so far! You are almost done :+1:  :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight:
- Good job with the gitflow :+1:
- Good PR description :clap: 

## Required Changes ♻️ 
- [ ] _Check the comments below :arrow_double_down: _

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-21 21:51 UTC, GzimAsani commented on modules/Switchsections.js
> +/* eslint-disable linebreak-style */
- [ ] It is not a good practice to disable linters. Remember they're there to help you write a better code. If you think that disabling them is very necessary for a reason, please explain it here for the next reviewer.

2022-03-22 07:50 UTC, Mihndim2020 requested changes
## Hi @, 

Great work on making the changes requested by a previous reviewer 👏 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![stay-strong-youre-almost-there](https://user-images.githubusercontent.com/65852621/133678845-1b015b27-e9bc-4784-a316-bc699db8237a.jpg)

 # Status: Requires Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 07:50 UTC, Mihndim2020 commented on modules/Switchsections.js
> +const navItem = document.querySelector('.nav_items');
- [ ] Great job implementing the changes requested by the previous code reviewer, but your app is broken, the links to `add  a new book` and `contacts page` are not longer working. I am unable to add a new book or visit the contacts page when I click on the links. Please It will be nice to fix that since it is a requirement for this project.

2022-03-22 08:35 UTC, IfzaRasool commented on modules/Switchsections.js
> +const navItem = document.querySelector('.nav_items');
It's working from the side. I Check many times but it's working fine. The live demo link will be damaged because of the luxon library and its work after the merging so please next code viewer contact with me on slack if have the same issue.

2022-03-22 08:42 UTC, moise10r approved these changes
### Hi @IfzaRasool, 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @moise10r when you comment so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 08:43 UTC, moise10r commented on modules/Switchsections.js
> +const navItem = document.querySelector('.nav_items');
Great job @IfzaRasool :+1:

2022-03-22 09:59 UTC, merged